return {
    s(
        {
            trig="ff",
        },
        {
            t("\\frac{"),
            i(1),
            t("}{"),
            i(2),
            t("}")
        }
    ),
    s(
        {
            trig="im",
        },
        {
            t("$"),
            i(1),
            t("$"),
        }
    ),
    s(
        {
            trig="dm",
        },
        {
            t({"$$", ""}),
            i(1),
            t({"", "$$"}),
        }
    ),
    s(
        {
            trig="bc",
        },
        {
            t("\\left\\{"),
            i(1),
            t("\\right\\}"),
        }
    ),
    s(
        {
            trig="bb",
        },
        {
            t("\\left["),
            i(1),
            t("\\right]"),
        }
    ),
    s(
        {
            trig="bp",
        },
        {
            t("\\left("),
            i(1),
            t("\\right)"),
        }
    ),
    s(
        {
            trig="pri",
            wordTrig=false,
        },
        {
            t("^{("),
            i(1),
            t(")}")
        }
    ),
    s(
        {
            trig="jacobian",
        },
        {
            t("\\mathbb{J}")
        }
    ),
}
