autoload -Uz vcs_info compinit promptinit

promptinit
compinit

setopt PROMPT_SUBST

CONFIG_DIR=${${(%):-%x}:A:h}
source ${CONFIG_DIR}/alias

zstyle ':vcs_info:git*' formats "  %F{3}%b%f"
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr ' %F{green}✚%f'
zstyle ':vcs_info:*' unstagedstr ' %F{red}●%f'

precmd() {
    vcs_info
}


PROMPT='[$USER@$HOST] %B%F{4}%~%f%b${vcs_info_msg_0_} $ '
